CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(200) NOT NULL UNIQUE,
  password_digest VARCHAR(60) NOT NULL
);

CREATE TABLE spaces (
  id SERIAL PRIMARY KEY,
  name VARCHAR(60) NOT NULL,
  description VARCHAR(240) NOT NULL,
  price INTEGER NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);
